### ISSUE TITLE
How to use this script on bigsur

### ISSUE THREAD

**Issue by ciscohack** [p00ya/displaymode#4]
**Desktop (please complete the following information):**
 - OS: macOS bigSur
 - Device: [MacBook Pro (16-inch, 2019)]

**Additional context**
Hi Team,

Can someone help how to run this script on macOS bigsur. I downloaded the zip file and trying to run the command from directory it's not working. i give the execution permission as well.

-Praveen

**Comment by p00ya** [comment]
Hi there - I've updated the documentation, please see the installation instructions at https://github.com/p00ya/displaymode .  If there are any problems let me know on this issue, `displaymode` should work fine on Big Sur once it's been signed.
