### ISSUE TITLE
Select specific refresh rate when there are multiple with the same resolution

### ISSUE THREAD

**Issue by hippydave** [p00ya/displaymode#8]
Hi, thanks for this tool, it's great.

Running
displaymode d
on my MBP gives a long list of resolutions, with multiple refresh rates available for them. If I run
displaymode t 1440 900
it successfully sets the screen mode to one of the instances of that resolution, it's the first in the list so that may be why it's chosen, but it would be great if I could choose which refresh rate to use for the resolution I specify.

For completeness, the mode it's set to is 59.9Hz, the one I'd like to choose is 60.0Hz (not a massive difference I'll admit), and here's the long list displaymode d shows:

Display 0 (MAIN):
3072 x 1920 @59.9Hz
3072 x 1920 @50.0Hz
3072 x 1920 @48.0Hz
3072 x 1920 @48.0Hz
3072 x 1920 @60.0Hz
1536 x 960 @59.9Hz
3584 x 2240 @59.9Hz
2688 x 1680 @59.9Hz
2304 x 1440 @59.9Hz
1650 x 1050 @59.9Hz
1440 x 900 @59.9Hz *
1280 x 800 @59.9Hz
1152 x 720 @59.9Hz
1024 x 768 @59.9Hz
840 x 524 @59.9Hz !
800 x 600 @59.9Hz
640 x 480 @59.9Hz !
1536 x 960 @50.0Hz
3584 x 2240 @50.0Hz
2688 x 1680 @50.0Hz
2304 x 1440 @50.0Hz
1650 x 1050 @50.0Hz
1440 x 900 @50.0Hz
1280 x 800 @50.0Hz
1152 x 720 @50.0Hz
1024 x 768 @50.0Hz
840 x 524 @50.0Hz !
800 x 600 @50.0Hz
640 x 480 @50.0Hz !
1536 x 960 @48.0Hz
3584 x 2240 @48.0Hz
2688 x 1680 @48.0Hz
2304 x 1440 @48.0Hz
1650 x 1050 @48.0Hz
1440 x 900 @48.0Hz
1280 x 800 @48.0Hz
1152 x 720 @48.0Hz
1024 x 768 @48.0Hz
840 x 524 @48.0Hz !
800 x 600 @48.0Hz
640 x 480 @48.0Hz !
1536 x 960 @48.0Hz
3584 x 2240 @48.0Hz
2688 x 1680 @48.0Hz
2304 x 1440 @48.0Hz
1650 x 1050 @48.0Hz
1440 x 900 @48.0Hz
1280 x 800 @48.0Hz
1152 x 720 @48.0Hz
1024 x 768 @48.0Hz
840 x 524 @48.0Hz !
800 x 600 @48.0Hz
640 x 480 @48.0Hz !
1536 x 960 @60.0Hz
3584 x 2240 @60.0Hz
2688 x 1680 @60.0Hz
2304 x 1440 @60.0Hz
1650 x 1050 @60.0Hz
1440 x 900 @60.0Hz
1280 x 800 @60.0Hz
1152 x 720 @60.0Hz
1024 x 768 @60.0Hz
840 x 524 @60.0Hz !
800 x 600 @60.0Hz
640 x 480 @60.0Hz !

Many thanks!

**Comment by p00ya** [comment]
Hi, thanks for the suggestion, it should be easy to add.

**Comment by p00ya** [comment]
Hi, I've pushed the refresh rate feature to the "refresh" branch for testing.  You can give it a try:

```
git clone https://github.com/p00ya/displaymode.git
cd displaymode
git switch refresh
clang -g -std=c11 -lm -framework CoreFoundation -framework CoreGraphics -o displaymode displaymode.c
./displaymode t 1440 900 @60.0
```

Please let me know how it goes for you.

**Comment by hippydave** [comment]
Hi, yes it works great - thanks so much for the quick update!
